/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as MapRouteImport } from './routes/map'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApartmentsAptNoRouteImport } from './routes/apartments.$aptNo'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsCodeRouteImport } from './routes/standards.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsAptNoRoute = ApartmentsAptNoRouteImport.update({
  id: '/apartments/$aptNo',
  path: '/apartments/$aptNo',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsCodeRoute = StandardsCodeRouteImport.update({
  id: '/standards/$code',
  path: '/standards/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/drawings': typeof DrawingsRoute
  '/map': typeof MapRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
  '/standards/$code': typeof StandardsCodeRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/drawings': typeof DrawingsRoute
  '/map': typeof MapRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
  '/standards/$code': typeof StandardsCodeRoute
  '/standards': typeof StandardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/drawings': typeof DrawingsRoute
  '/map': typeof MapRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
  '/standards/$code': typeof StandardsCodeRoute
  '/standards/': typeof StandardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/drawings'
    | '/map'
    | '/qa'
    | '/schedule'
    | '/tasks'
    | '/apartments/$aptNo'
    | '/standards/$code'
    | '/standards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/drawings'
    | '/map'
    | '/qa'
    | '/schedule'
    | '/tasks'
    | '/apartments/$aptNo'
    | '/standards/$code'
    | '/standards'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/drawings'
    | '/map'
    | '/qa'
    | '/schedule'
    | '/tasks'
    | '/apartments/$aptNo'
    | '/standards/$code'
    | '/standards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  DrawingsRoute: typeof DrawingsRoute
  MapRoute: typeof MapRoute
  QaRoute: typeof QaRoute
  ScheduleRoute: typeof ScheduleRoute
  TasksRoute: typeof TasksRoute
  ApartmentsAptNoRoute: typeof ApartmentsAptNoRoute
  StandardsCodeRoute: typeof StandardsCodeRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$aptNo': {
      id: '/apartments/$aptNo'
      path: '/apartments/$aptNo'
      fullPath: '/apartments/$aptNo'
      preLoaderRoute: typeof ApartmentsAptNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$code': {
      id: '/standards/$code'
      path: '/standards/$code'
      fullPath: '/standards/$code'
      preLoaderRoute: typeof StandardsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  DrawingsRoute: DrawingsRoute,
  MapRoute: MapRoute,
  QaRoute: QaRoute,
  ScheduleRoute: ScheduleRoute,
  TasksRoute: TasksRoute,
  ApartmentsAptNoRoute: ApartmentsAptNoRoute,
  StandardsCodeRoute: StandardsCodeRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
