/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as MapRouteImport } from './routes/map'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as QaRouteImport } from './routes/qa'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApartmentsAptNoRouteImport } from './routes/apartments.$aptNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsAptNoRoute = ApartmentsAptNoRouteImport.update({
  id: '/apartments/$aptNo',
  path: '/apartments/$aptNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/audit': typeof AuditRoute
  '/drawings': typeof DrawingsRoute
  '/finance': typeof FinanceRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/standards': typeof StandardsRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/audit': typeof AuditRoute
  '/drawings': typeof DrawingsRoute
  '/finance': typeof FinanceRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/standards': typeof StandardsRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/audit': typeof AuditRoute
  '/drawings': typeof DrawingsRoute
  '/finance': typeof FinanceRoute
  '/map': typeof MapRoute
  '/mobile': typeof MobileRoute
  '/qa': typeof QaRoute
  '/schedule': typeof ScheduleRoute
  '/standards': typeof StandardsRoute
  '/tasks': typeof TasksRoute
  '/apartments/$aptNo': typeof ApartmentsAptNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/audit'
    | '/drawings'
    | '/finance'
    | '/map'
    | '/mobile'
    | '/qa'
    | '/schedule'
    | '/standards'
    | '/tasks'
    | '/apartments/$aptNo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/audit'
    | '/drawings'
    | '/finance'
    | '/map'
    | '/mobile'
    | '/qa'
    | '/schedule'
    | '/standards'
    | '/tasks'
    | '/apartments/$aptNo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/audit'
    | '/drawings'
    | '/finance'
    | '/map'
    | '/mobile'
    | '/qa'
    | '/schedule'
    | '/standards'
    | '/tasks'
    | '/apartments/$aptNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  AuditRoute: typeof AuditRoute
  DrawingsRoute: typeof DrawingsRoute
  FinanceRoute: typeof FinanceRoute
  MapRoute: typeof MapRoute
  MobileRoute: typeof MobileRoute
  QaRoute: typeof QaRoute
  ScheduleRoute: typeof ScheduleRoute
  StandardsRoute: typeof StandardsRoute
  TasksRoute: typeof TasksRoute
  ApartmentsAptNoRoute: typeof ApartmentsAptNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/$aptNo': {
      id: '/apartments/$aptNo'
      path: '/apartments/$aptNo'
      fullPath: '/apartments/$aptNo'
      preLoaderRoute: typeof ApartmentsAptNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  AuditRoute: AuditRoute,
  DrawingsRoute: DrawingsRoute,
  FinanceRoute: FinanceRoute,
  MapRoute: MapRoute,
  MobileRoute: MobileRoute,
  QaRoute: QaRoute,
  ScheduleRoute: ScheduleRoute,
  StandardsRoute: StandardsRoute,
  TasksRoute: TasksRoute,
  ApartmentsAptNoRoute: ApartmentsAptNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
